services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST= PUBLIC_IP
      - PASSWORD_HASH= PASSWORD_HASH
      - WG_DEFAULT_ADDRESS=10.13.13.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=172.20.0.0/16
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_PORT=51820
      - WG_UI_PORT=51821
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wg-easy-data:/etc/wireguard:Z
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      vpn-network:
        ipv4_address: 172.20.0.2
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - MOODLE_URL=${MOODLE_URL}
      - DEV=${DEV}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PLANS_JSON_URL=${PLANS_JSON_URL}
      - WERKZEUG_RUN_MAIN=${WERKZEUG_RUN_MAIN}
      - ENABLE_COMPARER=${ENABLE_COMPARER}
      - PUSHOVER_KEY=${PUSHOVER_KEY}
      - PUSHOVER_USER=${PUSHOVER_USER}
      - SENTRY_DSN=${SENTRY_DSN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      vpn-network:
        ipv4_address: 172.20.0.20
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      vpn-network:
        ipv4_address: 172.20.0.10
    command: ["mongod", "--bind_ip_all"]
  frontend:
    build: ./frontend
    container_name: www-plan
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "81:5000"
    networks:
      vpn-network:
        ipv4_address: 172.20.0.30
    depends_on:
      - mongodb
      - backend
networks:
  vpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
volumes:
  mongodb_data:
  wg-easy-data: